/* CREATE crash table */
CREATE TABLE IF NOT EXISTS crash (
BELTED_DEATH_COUNT INTEGER 
, BICYCLE_DEATH_COUNT INTEGER
, COLLISION_TYPE INTEGER
, CRASH_MONTH INTEGER
, CRASH_YEAR INTEGER
, DAY_OF_WEEK INTEGER
, DEC_LAT DECIMAL
, DEC_LONG DECIMAL
, FATAL_COUNT INTEGER
, HOUR_OF_DAY INTEGER
, INJURY_COUNT INTEGER
, INTERSECT_TYPE INTEGER
, MCYCLE_DEATH_COUNT INTEGER
, PED_DEATH_COUNT INTEGER
, CRASH_REPORT_NUMBER INTEGER
, GEOM TEXT
, ZIP TEXT
)