/*Create flag table*/
CREATE TABLE IF NOT EXISTS flag (
	aggressive_driving INTEGER
	,	alcohol_related INTEGER
	, 	angle_crash INTEGER
	, 	atv	INTEGER
	,	backup_congestion INTEGER
	,	backup_nonrecurring INTEGER
	,	backup_prior INTEGER
	, 	bicycle INTEGER
	,	cell_phone INTEGER
	,	comm_vehicle INTEGER
	, 	core_network INTEGER
	, 	crn INTEGER
	, 	cross_median INTEGER
	,	curved_road INTEGER
	, 	curve_dvr_error INTEGER
	, 	deer_related INTEGER
	, 	distracted INTEGER
	, 	drinking_driver INTEGER
	, 	driver_16yr INTEGER
	, 	driver_17yr INTEGER
	, 	driver_18yr INTEGER
	, 	driver_19yr INTEGER
	, 	driver_20yr INTEGER
	, 	driver_50_64yr INTEGER
	,	driver_65_74yr INTEGER
	, 	driver_75plus INTEGER
	,	drugged_driver INTEGER
	, 	drug_related INTEGER
	, 	fatal INTEGER
	, 	fatal_or_susp_serious_inj INTEGER
	, 	fatigue_asleep INTEGER
	, 	fire_in_vehicle INTEGER
	, 	hazardous_truck INTEGER
	, 	hit_barrier INTEGER
	, 	hit_bridge INTEGER
	, 	hit_deer INTEGER
	, 	hit_embankment INTEGER
	, 	hit_fixed_object INTEGER
	, 	hit_gdrail INTEGER
	,  	hit_gdrail_end INTEGER
	, 	hit_parked_vehicle INTEGER
	, 	hit_pole INTEGER
	, 	hit_tree_shrub INTEGER
	, 	horse_buggy INTEGER
	, 	ho_oppdir_sdswp INTEGER
	, 	hvy_truck_related INTEGER
	, 	icy_road INTEGER
	, 	illegal_drug_related INTEGER
	, 	illumination_dark INTEGER
	,	impaired_driver INTEGER
	, 	injury INTEGER
	, 	injury_or_fatal INTEGER
	, 	intersection INTEGER
	, 	interstate INTEGER
	, 	lane_departure INTEGER
	, 	left_turn INTEGER
	, 	limit_65mph INTEGER
	, 	limit_70mph INTEGER
	, 	local_road INTEGER
	, 	local_road_only INTEGER
	, 	mc_drinking_driver INTEGER
	, 	motorcycle INTEGER
	, 	multiple_vehicle INTEGER
	, 	nhtsa_agg_driving INTEGER
	, 	non_intersection INTEGER
	, 	no_clearance INTEGER
	,	opioid_related INTEGER
	, 	other_freeway INTEGER
	, 	overturned INTEGER
	, 	pedestrian INTEGER
	,	phantom_vehicle INTEGER
	, 	possible_injury INTEGER
	, 	property_damage_only INTEGER
	, 	psp_reported INTEGER
	, 	rear_end INTEGER
	, 	running_red_lt INTEGER
	,	running_stop_sign INTEGER
	,	rural INTEGER
	, 	school_bus INTEGER
	, 	school_zone INTEGER
	, 	shldr_related INTEGER
	, 	signalized_int INTEGER
	, 	single_vehicle INTEGER
	, 	snowmobile INTEGER
	, 	snow_slush_road INTEGER
	, 	speeding INTEGER
	, 	speeding_related INTEGER
	, 	state_road INTEGER
	, 	stop_controlled_int INTEGER
	, 	sudden_deer INTEGER
	, 	suspected_minor_injury INTEGER
	, 	suspected_serious_injury INTEGER
	, 	sv_run_off_rd INTEGER
	, 	tailgating INTEGER
	, 	train INTEGER
	, 	train_trolley INTEGER
	, 	trolley INTEGER
	, 	turnpike INTEGER
	, 	unbelted INTEGER
	, 	underage_drnk_drv INTEGER
	, 	unlicensed INTEGER
	, 	unsignalized_int INTEGER
	, 	urban INTEGER
	, 	vehicle_failure INTEGER
	, 	vehicle_towed INTEGER
	, 	wet_road INTEGER
	, 	work_zone INTEGER
	, 	year_county TEXT
)